### ISSUE TITLE
Install実行時、jquery-ui のdialogでエラー発生

### ISSUE THREAD

**Issue by RikaFujiwara** [NetCommons3/Install#5]
2015/06/24に、まっさらな状態からインストールを実行。

Install画面を表示して実行したところ、InstallプラグインでJSエラーが出ました。
jquery-ui.min.jsが見つからないとのこと。
Plugin/Install/View/Layouts/default.ctp で行っている
'/components/jqueryui/jquery-ui.min.js',
が見つからないエラーになっている

実際にapp/webroot/components下のjqueryuiでは
'/components/jqueryui/ui/minified/jquery-ui.min.js',
が正しい位置のようです

これは上記Ctpのパスが間違っているのか、それともjquery-uiを入れるときに何か失敗して環境を損なっているのでしょうか？

**Comment by s-nakajima** [comment]
Installプラグインは、修正しました。ただ、NetCommons3のcomposer.lockファイルは未修正です。そのため、composer updateをしてください。

**Comment by s-nakajima** [comment]
現在、解決しているためCloseする
