### ISSUE TITLE
インストール完了画面のForm

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Install#9]
https://github.com/NetCommons3/Install/blob/master/View/Install/finish.ctp

FormHelperを利用し、submitしています。
submit先はトップページですが、PagesプラグインでSecurityコンポーネントを使用するとBlack holeになります。
（Tokenがないため。）

リンクボタンで良いと思いますが、Submitしているのは何かあったのでしょうか？

**Comment by s-nakajima** [comment]
西川さんが作った時からのものです。理由は西川さんに聞いてください。
私もリンクボタンで良いと思います。特に理由はなければ、何かのついでにリンクボタンにするように修正します。

**Comment by kteraguchi** [comment]
Securityコンポーネントを組み込む方向にします。

**Comment by s-nakajima** [comment]
https://github.com/NetCommons3/Install/commit/93ede8c1e88fafa687c4cf0acb08866a398a5dfa
